<?php

/**
 * PluginMemberResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMemberResourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMemberResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMemberResource');
    }
}