<?php

/**
 * PluginProjectResourceMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProjectResourceMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProjectResourceMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginProjectResourceMaster');
    }

    public function retrieveOne($options)
    {
      $_result = $this->createQuery('prm');
      if (isset($options['id'])) $_result->addWhere('prm.id = ?', $options['id']);
      if (isset($options['member_id'])) $_result->addWhere('prm.member_id = ?', $options['member_id']);
      if (isset($options['project_id'])) $_result->addWhere('prm.project_id = ?', $options['project_id']);
      if (isset($options['day'])) $_result->addWhere('prm.day = ?', $options['day']);
      if (isset($options['status'])) $_result->addWhere('prm.status = ?', $options['status']);

      return $_result->fetchOne();
    }
   
}
